import 'package:flutter/material.dart';

/// Per-scheme colour set behind [Palette]. Mirrors PaletteTokens.kt byte-for-byte.
@immutable
class PaletteTokens {
  final Color surfaceBase, surfaceRaised, surfaceOverlay, surfaceInset;
  final Color hairline, hairlineStrong;
  final Color textPrimary, textSecondary, textTertiary;
  final Color glowAmbient;
  final Color accent, accentHover, accentMuted, focusRing;
  final Color recovery000, recovery030, recovery055, recovery078, recovery100;
  final Color strain000, strain033, strain066, strain100;
  final Color sleepAwake, sleepLight, sleepDeep, sleepREM;
  final Color zone1, zone2, zone3, zone4, zone5;
  final Color statusPositive, statusWarning, statusCritical;
  final Color metricCyan, metricPurple, metricAmber, metricRose;
  final Color chargeColor, chargeDeep, chargeBright, chargeGlow;
  final Color effortColor, effortDeep, effortBright, effortGlow;
  final Color restColor, restDeep, restBright, restGlow;
  final Color stressColor, stressDeep, stressBright, stressGlow;
  final Color scenicCenter, scenicEdge, scenicStar;
  final Color cardFillTop, cardFillBottom;
  final Color gold, goldLight, goldDeep, goldDeepText, signalYellow;
  final Color titaniumTop, titaniumMid, titaniumLow, titaniumDeep;
  final Color tipCore;

  const PaletteTokens({
    required this.surfaceBase,
    required this.surfaceRaised,
    required this.surfaceOverlay,
    required this.surfaceInset,
    required this.hairline,
    required this.hairlineStrong,
    required this.textPrimary,
    required this.textSecondary,
    required this.textTertiary,
    required this.glowAmbient,
    required this.accent,
    required this.accentHover,
    required this.accentMuted,
    required this.focusRing,
    required this.recovery000,
    required this.recovery030,
    required this.recovery055,
    required this.recovery078,
    required this.recovery100,
    required this.strain000,
    required this.strain033,
    required this.strain066,
    required this.strain100,
    required this.sleepAwake,
    required this.sleepLight,
    required this.sleepDeep,
    required this.sleepREM,
    required this.zone1,
    required this.zone2,
    required this.zone3,
    required this.zone4,
    required this.zone5,
    required this.statusPositive,
    required this.statusWarning,
    required this.statusCritical,
    required this.metricCyan,
    required this.metricPurple,
    required this.metricAmber,
    required this.metricRose,
    required this.chargeColor,
    required this.chargeDeep,
    required this.chargeBright,
    required this.chargeGlow,
    required this.effortColor,
    required this.effortDeep,
    required this.effortBright,
    required this.effortGlow,
    required this.restColor,
    required this.restDeep,
    required this.restBright,
    required this.restGlow,
    required this.stressColor,
    required this.stressDeep,
    required this.stressBright,
    required this.stressGlow,
    required this.scenicCenter,
    required this.scenicEdge,
    required this.scenicStar,
    required this.cardFillTop,
    required this.cardFillBottom,
    required this.gold,
    required this.goldLight,
    required this.goldDeep,
    required this.goldDeepText,
    required this.signalYellow,
    required this.titaniumTop,
    required this.titaniumMid,
    required this.titaniumLow,
    required this.titaniumDeep,
    required this.tipCore,
  });
}

/// WHOOP-reset dark palette (blue-grey canvas, red→yellow→green recovery).
const darkTokens = PaletteTokens(
  surfaceBase: Color(0xFF121518),
  surfaceRaised: Color(0xFF25292C),
  surfaceOverlay: Color(0xFF1C1F26),
  surfaceInset: Color(0xFF1F2229),
  hairline: Color(0xFF21304A),
  hairlineStrong: Color(0xFF2E3C57),
  textPrimary: Color(0xFFF4F6F8),
  textSecondary: Color(0xFFC8CFD8),
  textTertiary: Color(0xFF8A94A4),
  glowAmbient: Color(0xFF3A2D0A),
  accent: Color(0xFF60A0E0),
  accentHover: Color(0xFF8FBEEC),
  accentMuted: Color(0xFF16233A),
  focusRing: Color(0xFF60A0E0),
  recovery000: Color(0xFFE0463C),
  recovery030: Color(0xFFE8743C),
  recovery055: Color(0xFFF9DF4A),
  recovery078: Color(0xFF8FD86A),
  recovery100: Color(0xFF03E095),
  strain000: Color(0xFF9C5A14),
  strain033: Color(0xFFC2762A),
  strain066: Color(0xFFD98A3D),
  strain100: Color(0xFFF0A85A),
  sleepAwake: Color(0xFFC2CCDA),
  sleepLight: Color(0xFF4A90E2),
  sleepDeep: Color(0xFF2F6FCB),
  sleepREM: Color(0xFF6FA8E8),
  zone1: Color(0xFF4A90E2),
  zone2: Color(0xFF3FA9C9),
  zone3: Color(0xFFE8B84B),
  zone4: Color(0xFFD98A3D),
  zone5: Color(0xFFE0662F),
  statusPositive: Color(0xFF03E095),
  statusWarning: Color(0xFFF0A020),
  statusCritical: Color(0xFFE0662F),
  metricCyan: Color(0xFF3FA9C9),
  metricPurple: Color(0xFF4A90E2),
  metricAmber: Color(0xFFD98A3D),
  metricRose: Color(0xFFE0662F),
  chargeColor: Color(0xFF03E095),
  chargeDeep: Color(0xFF0B9D62),
  chargeBright: Color(0xFF6BF0B4),
  chargeGlow: Color(0xFF03E095),
  effortColor: Color(0xFF4090E0),
  effortDeep: Color(0xFF2A6FB0),
  effortBright: Color(0xFF74B6F0),
  effortGlow: Color(0xFF4090E0),
  restColor: Color(0xFF83A0B8),
  restDeep: Color(0xFF2F6FCB),
  restBright: Color(0xFF6FA8E8),
  restGlow: Color(0xFF4A90E2),
  stressColor: Color(0xFFF0A020),
  stressDeep: Color(0xFF4A90E2),
  stressBright: Color(0xFFE0662F),
  stressGlow: Color(0xFFF0A020),
  scenicCenter: Color(0xFF1C2128),
  scenicEdge: Color(0xFF121518),
  scenicStar: Color(0xFFC8CFD8),
  cardFillTop: Color(0xFF15243C),
  cardFillBottom: Color(0xFF0B1424),
  gold: Color(0xFF60A0E0),
  goldLight: Color(0xFF9FC8F0),
  goldDeep: Color(0xFF3A78C8),
  goldDeepText: Color(0xFFFFFFFF),
  signalYellow: Color(0xFFFFD63D),
  titaniumTop: Color(0xFFF1F3F5),
  titaniumMid: Color(0xFFC9CFD4),
  titaniumLow: Color(0xFF969DA4),
  titaniumDeep: Color(0xFF6B737B),
  tipCore: Color(0xFFFFFFFF),
);

/// Soft, premium light scheme (Apple-Health-like): a cool neutral light-grey
/// canvas with white cards floating on gentle shadows, near-black text — and the
/// SAME vivid data hues as [darkTokens], each darkened ~10–14% so recovery reads
/// green, sleep blue and strain/effort orange on white without going neon.
const lightTokens = PaletteTokens(
  surfaceBase: Color(0xFFECEDEF),
  surfaceRaised: Color(0xFFFFFFFF),
  surfaceOverlay: Color(0xFFFFFFFF),
  surfaceInset: Color(0xFFE0E2E6),
  hairline: Color(0xFFDADCE0),
  hairlineStrong: Color(0xFFC7CAD0),
  textPrimary: Color(0xFF1A2230),
  textSecondary: Color(0xFF4C5564),
  textTertiary: Color(0xFF7C8696),
  glowAmbient: Color(0xFFE9EDF3),
  accent: Color(0xFF2F6FCB),
  accentHover: Color(0xFF255CB0),
  accentMuted: Color(0xFFE4ECF6),
  focusRing: Color(0xFF2F6FCB),
  recovery000: Color(0xFFC33D34),
  recovery030: Color(0xFFCA6534),
  recovery055: Color(0xFFD8A62E),
  recovery078: Color(0xFF6FBE55),
  recovery100: Color(0xFF06BE80),
  strain000: Color(0xFF9C5A14),
  strain033: Color(0xFFBE6E22),
  strain066: Color(0xFFCE7C2C),
  strain100: Color(0xFFE58F3E),
  sleepAwake: Color(0xFF98A2B2),
  sleepLight: Color(0xFF3A80D6),
  sleepDeep: Color(0xFF234F9E),
  sleepREM: Color(0xFF5790DA),
  zone1: Color(0xFF3A80D6),
  zone2: Color(0xFF2E92B4),
  zone3: Color(0xFFC99A2A),
  zone4: Color(0xFFC2792E),
  zone5: Color(0xFFC84E1E),
  statusPositive: Color(0xFF12A56E),
  statusWarning: Color(0xFFD08A1C),
  statusCritical: Color(0xFFC84E1E),
  metricCyan: Color(0xFF2E92B4),
  metricPurple: Color(0xFF3A80D6),
  metricAmber: Color(0xFFC2792E),
  metricRose: Color(0xFFC84E1E),
  chargeColor: Color(0xFF12A56E),
  chargeDeep: Color(0xFF0B7D50),
  chargeBright: Color(0xFF5FCF9C),
  chargeGlow: Color(0xFF12A56E),
  effortColor: Color(0xFFCE7C2C),
  effortDeep: Color(0xFF9C5714),
  effortBright: Color(0xFFE0954A),
  effortGlow: Color(0xFFCE7C2C),
  restColor: Color(0xFF3A80D6),
  restDeep: Color(0xFF234F9E),
  restBright: Color(0xFF5790DA),
  restGlow: Color(0xFF3A80D6),
  stressColor: Color(0xFFD08A1C),
  stressDeep: Color(0xFF3A80D6),
  stressBright: Color(0xFFC84E1E),
  stressGlow: Color(0xFFD08A1C),
  scenicCenter: Color(0xFFF2F3F5),
  scenicEdge: Color(0xFFE7E9EC),
  scenicStar: Color(0xFFDADCE0),
  cardFillTop: Color(0xFFFFFFFF),
  cardFillBottom: Color(0xFFF7F8FA),
  gold: Color(0xFFC79320),
  goldLight: Color(0xFFE0B24C),
  goldDeep: Color(0xFF8F6712),
  goldDeepText: Color(0xFF3A2708),
  signalYellow: Color(0xFFD89A00),
  titaniumTop: Color(0xFFDDE1E6),
  titaniumMid: Color(0xFFBBC2C9),
  titaniumLow: Color(0xFF98A0A8),
  titaniumDeep: Color(0xFF6B737B),
  tipCore: Color(0xFF1A2230),
);
